/**
 * MTG-flavored quotes shown in the home page eyebrow.
 * Mix of real flavor text, community memes, and Izzet lab humor.
 * Keep entries short enough to fit on one line in the eyebrow slot.
 */
export const MTG_QUOTES: readonly string[] = [
  // ── Actual flavor text ──────────────────────────────────────────────────
  "Ach! Hans, run! It's the Lhurgoyf!",
  "The land promises nothing and keeps its promise.",
  "You should fight everything with fire. — Jaya Ballard",
  "He's the unlife of the party.",
  "Sorry I burned down your village. Here's some gold.",
  "After thoughtful contemplation, most barbarians choose force.",
  "It's probably nothing.",
  "Each reality is but the dream of another.",
  "Don't you mean 'poisonous'? — AGGHHH!",
  "Wield your heart, and the world will tremble.",
  "Some convictions are so strong the world must break.",
  "Step 1: find your cousin. Step 2: get cousin in the cannon.",
  "Throw enough goblins at any problem and it should go away.",
  "He's smart for a goblin. He can hit and run.",
  "Gnshhagghkkapphribbit. — Yargle",
  "Day 31: experiment succeeded! Day 30: I might have a problem.",
  "Yes, your opponent can't even. We know.",
  "FLAPPIN. DOUBLE SLAPPIN. NO NAPPIN. SCRAPPIN.",
  "I know what you're going to draw. I put it there.",
  "It was inevitable, really. — Elesh Norn, probably",

  // ── Community memes & in-jokes ───────────────────────────────────────────
  "Dies to removal.",
  "Needs more Goyf.",
  "Bolt the Bird.",
  "In response…",
  "I'm tapped out.",
  "That's a lot of triggers.",
  "Exile is the new grave.",
  "Reading the card explains the card.",
  "Symmetrical effects are fair and balanced.",
  "Dies to Doom Blade.",
  "Magical Christmas Land.",
  "Bolas always wins.",
  "This [X] is now a 3/3 Elk.",
  "My deck is about a 7, I think.",
  "Magic as Richard Garfield intended.",
  "Sorin is still stuck in a rock.",
  "It is the will of Zedruu.",
  "Don't worry, it's not that kind of Zur deck.",
  "Guess we're playing Archenemy now.",
  "RTFC.",
  "WOW. FUCK. TRON.",
  "And yet it still dies to Doom Blade.",
  "Don't mess with horseshoe crabs.",
  "N(U)PE.",
  "Scoop.",
  "It's Glarbin' time.",
  "We did it, we finally broke Modern!",
  "Rosewater confirms everything.",
  "Philosophers in Magic are hardened badasses.",
  "Cat dad betrayal.",
  "All glory to the Gitrog Monster.",
  "Urabrask is a total bro.",
  "Jace has special bad ideas.",
  "Lukka fucks up again.",

  // ── Izzet / spellslinger flavor ──────────────────────────────────────────
  "For science.",
  "Hypothesis: confirmed. Lab: on fire.",
  "Zap first. Questions after the autopsy.",
  "The Izzet motto: 'Hold my beaker.'",
  "The Izzet League wishes to inform you: oops.",
  "Research notes: everything is on fire. Excellent.",
  "According to my calculations, you should run.",
  "Curiosity may have killed the cat. Worth it.",
  "The experiment was a success. Mostly.",
  "Niv-Mizzet approves of your curiosity.",
  "The storm count is… relevant.",
  "Two mana, one spell, zero regrets.",

  // ── In-game truths ───────────────────────────────────────────────────────
  "Protection from common sense.",
  "Tap: deal damage to your relationship with this game.",
  "Everything dies. That's not a problem, that's a plan.",
  "Storm is a fair mechanic, actually.",
  "The stack: where dreams go to die.",
  "Wait, does this trigger?",
  "Priority? I'll take it, thanks.",
  "Mana screw builds character.",
  "I flooded out. On turn 12.",
  "Going infinite in 12 easy steps.",
  "The combo works in Magical Christmas Land.",
  "Target player's mind is blown.",
  "All according to plan. (While losing.)",
  "'No blocks.' — the most feared words at the table",
  "Draw, go. — the blue player's battle hymn",
  "My hand is perfect. My lands are not.",
  "One more cantrip and I'll know what to do.",
  "I'm dead on board. I draw anyway.",
  "It's fine. I have the answer. Probably.",
  "Everything is fine. This is fine.",
  "Wrath clears the board. Temporarily.",
  "One more land and I can cast Emrakul.",
  "The graveyard is a resource. Mine's full.",
  "I cast Brainstorm and made things worse somehow.",
  "Counterspell. Because I can.",
  "The storm is… building.",
  "Technically it's a 'may' ability.",
  "Going to combat. Not attacking. Sending a message.",
  "My deck doesn't need a plan. It needs a miracle.",
  "The storm count is irrelevant. Until it isn't.",
  "Four Lava Spikes and a dream.",
  "Did you want to keep that creature? Asking for a friend.",
  "We are all just storm counts waiting to resolve.",
  "Jaya Ballard was right about everything.",
  "The plan: draw cards until a plan appears.",
  "Have you tried not being a bear?",
];

/** Returns a deterministic-per-render random quote from the list. */
export function pickRandomQuote(): string {
  return MTG_QUOTES[Math.floor(Math.random() * MTG_QUOTES.length)];
}
