/**
 * Centralised SEO helpers for Storm Count.
 *
 * Why this file exists
 * --------------------
 * Next.js shallowly merges `metadata` from layout → page and **replaces**
 * nested fields like `openGraph` and `twitter` wholesale when a page redeclares
 * them. Confirmed in `node_modules/next/dist/docs/01-app/03-api-reference/04-functions/generate-metadata.md`
 * (section "Merging → Overwriting fields").
 *
 * Without this helper, every per-page `openGraph` block in the codebase
 * silently drops the OG image declared on the root layout. These builders
 * always re-inject the canonical OG image so social cards keep working on
 * deep links.
 *
 * Every URL-bearing field is built off `BRAND.domain` so changing the domain
 * is a one-liner.
 */
import type { Metadata } from "next";
import { BRAND } from "@/lib/constants";

export const BASE_URL = `https://${BRAND.domain}`;

/** OG image is generated by `app/opengraph-image.tsx` and exposed at this path. */
const OG_IMAGE_PATH = "/opengraph-image.png";
const OG_IMAGE_SIZE = { width: 1200, height: 630 } as const;

/** Always-included alt text for the OG image. */
const OG_IMAGE_ALT = `${BRAND.name} — ${BRAND.tagline}`;

/** Compose an absolute URL from a path. Leading slash optional. */
export function absoluteUrl(path: string = "/"): string {
  if (!path.startsWith("/")) path = `/${path}`;
  return `${BASE_URL}${path}`;
}

type OgImage = {
  url: string;
  width?: number;
  height?: number;
  alt?: string;
};

const DEFAULT_OG_IMAGES: OgImage[] = [
  { url: OG_IMAGE_PATH, ...OG_IMAGE_SIZE, alt: OG_IMAGE_ALT },
];

type BuildMetadataInput = {
  /** Absolute path beginning with "/" (e.g. "/daily"). */
  path: string;
  /** Page-specific title (will be templated as "<title> | Storm Count" by layout). */
  title?: string;
  /** Page-specific meta description. Falls back to BRAND.description. */
  description?: string;
  /** Override Open Graph type. Defaults to "website". */
  ogType?: "website" | "article" | "profile";
  /** Force noindex on this page (e.g. /profile, /sign-in). */
  noindex?: boolean;
  /** Override images. Usually leave empty so the default OG card is used. */
  images?: OgImage[];
};

/**
 * Single source of truth for per-page metadata.
 *
 * Guarantees:
 *  - `alternates.canonical` is always set (relative — resolved by metadataBase)
 *  - `openGraph` is fully redeclared with images + locale (no silent drops)
 *  - `twitter` mirrors OG so the X/Twitter card renders correctly
 *  - `robots` is set when `noindex: true`
 */
export function buildMetadata({
  path,
  title,
  description,
  ogType = "website",
  noindex = false,
  images = DEFAULT_OG_IMAGES,
}: BuildMetadataInput): Metadata {
  const url = absoluteUrl(path);
  const desc = description ?? BRAND.description;

  const ogTitle = title ? `${title} | ${BRAND.name}` : `${BRAND.name} — ${BRAND.tagline}`;

  return {
    ...(title ? { title } : {}),
    description: desc,
    alternates: {
      canonical: path,
    },
    openGraph: {
      type: ogType,
      siteName: BRAND.name,
      title: ogTitle,
      description: desc,
      url,
      locale: BRAND.ogLocale,
      images,
    },
    twitter: {
      card: "summary_large_image",
      title: ogTitle,
      description: desc,
      images: images.map((i) => i.url),
    },
    ...(noindex
      ? {
          robots: {
            index: false,
            follow: true,
            googleBot: { index: false, follow: true },
          },
        }
      : {}),
  };
}

// ── JSON-LD builders ─────────────────────────────────────────────────────────
// All builders return plain objects to be stringified into a <script type="application/ld+json">.
// We keep the @context at the top level of each object so they can be embedded individually
// or combined under "@graph".

type Crumb = { name: string; path: string };

/**
 * BreadcrumbList — improves sitelink display and rich-result eligibility.
 * Pass the full breadcrumb trail including the current page.
 */
export function buildBreadcrumbList(crumbs: Crumb[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: crumbs.map((c, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: c.name,
      item: absoluteUrl(c.path),
    })),
  };
}

type FaqItem = { question: string; answer: string };

/**
 * FAQPage — eligible for rich snippets on Google when questions/answers are
 * genuinely present on the page. Do not generate FAQ markup for content that
 * isn't visible to users (per Google's structured data guidelines).
 */
export function buildFaqPage(items: FaqItem[]) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: items.map((it) => ({
      "@type": "Question",
      name: it.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: it.answer,
      },
    })),
  };
}

type VideoGameInput = {
  /** Path the game lives at — e.g. "/daily" or "/survival". */
  path: string;
  /** Display name — e.g. "Storm Count — Daily Challenge". */
  name: string;
  /** Short description shown in cards. */
  description: string;
  /** Optional sub-genre label. */
  genre?: string;
};

/**
 * VideoGame schema — a more precise alternative to SoftwareApplication for the
 * actual game modes. Helps disambiguate the entity ("a free MTG higher/lower
 * game") from the marketing site.
 */
export function buildVideoGame({
  path,
  name,
  description,
  genre = "Trivia",
}: VideoGameInput) {
  return {
    "@context": "https://schema.org",
    "@type": "VideoGame",
    "@id": `${absoluteUrl(path)}#videogame`,
    name,
    url: absoluteUrl(path),
    description,
    genre,
    gamePlatform: ["Web Browser"],
    applicationCategory: "GameApplication",
    operatingSystem: "Any",
    inLanguage: BRAND.htmlLang,
    publisher: {
      "@type": "Organization",
      name: BRAND.publisher,
      url: BASE_URL,
    },
    offers: {
      "@type": "Offer",
      price: "0",
      priceCurrency: "USD",
    },
  };
}

type HowToStep = { name: string; text: string };

/**
 * HowTo schema — augments the home page with the "how to play" steps.
 * Google has narrowed HowTo eligibility (mostly DIY/recipe-style), but the
 * markup is still understood as semantic content and helps AI search engines.
 */
export function buildHowTo({
  name,
  description,
  steps,
}: {
  name: string;
  description: string;
  steps: HowToStep[];
}) {
  return {
    "@context": "https://schema.org",
    "@type": "HowTo",
    name,
    description,
    step: steps.map((s, i) => ({
      "@type": "HowToStep",
      position: i + 1,
      name: s.name,
      text: s.text,
    })),
  };
}

/**
 * Convenience: serialise one or more JSON-LD objects ready for
 * `dangerouslySetInnerHTML`.
 */
export function jsonLd(...nodes: unknown[]): string {
  return JSON.stringify(nodes.length === 1 ? nodes[0] : nodes);
}
