import { NextResponse } from "next/server";
import { and, eq } from "drizzle-orm";
import { auth } from "@clerk/nextjs/server";
import { db } from "@/lib/db";
import { dailyScores } from "@/lib/db/schema";
import { getOrCreateDailySeed } from "@/lib/dailySeed";
import { todayUtc } from "@/lib/dates";

// Response is per-user (alreadyPlayed field), so no route-level cache.
export const dynamic = "force-dynamic";

// Themed-day generation makes ~10 sequential Scryfall calls — bump from
// the default 10s.
export const maxDuration = 60;

/**
 * GET /api/cards/daily
 *
 * Returns today's seeded card list plus whether the authenticated user has
 * already submitted a score today (checked against daily_scores in the DB).
 *
 * The seed is normally pre-generated by the `/api/cron/daily-seed` cron; if
 * it is missing, it is generated lazily here (see `getOrCreateDailySeed`,
 * which also handles themed days and concurrent first requests).
 */
export async function GET() {
  const today = todayUtc();

  // Optional auth — unauthenticated users always get alreadyPlayed: false.
  const { userId } = await auth();

  try {
    const seed = await getOrCreateDailySeed(today);

    let alreadyPlayed = false;
    if (userId) {
      const score = await db.query.dailyScores.findFirst({
        where: and(
          eq(dailyScores.userId, userId),
          eq(dailyScores.date, today),
        ),
        columns: { id: true },
      });
      alreadyPlayed = score != null;
    }

    return NextResponse.json({
      date: seed.date,
      themed: seed.themed ?? null,
      themedDescription: seed.themedDescription ?? null,
      cards: seed.cards,
      alreadyPlayed,
    });
  } catch (err) {
    console.error("[daily] error:", err);
    return NextResponse.json(
      { error: "Couldn't load today's challenge" },
      { status: 502 },
    );
  }
}
